export const mockServices = [
  {
    id: "1",
    name: "Nopa Restaurant",
    category: "dining",
    description:
      "Contemporary American cuisine with locally sourced ingredients and craft cocktails in a vibrant atmosphere.",
    rating: 4.6,
    reviewCount: 1247,
    priceRange: "$$$",
    distance: "0.8 mi",
    estimatedTime: "15 min",
    relevanceScore: 0.94,
    ctrPrediction: 0.12,
    cvrPrediction: 0.08,
    imageUrl: "/modern-restaurant-interior.png",
    tags: ["American", "Cocktails", "Date Night"],
  },
  {
    id: "2",
    name: "Hotel Zephyr",
    category: "hospitality",
    description: "Nautical-themed boutique hotel on Fisherman's Wharf with unique maritime decor and bay views.",
    rating: 4.4,
    reviewCount: 892,
    priceRange: "$$$$",
    distance: "1.2 mi",
    estimatedTime: "20 min",
    relevanceScore: 0.89,
    ctrPrediction: 0.09,
    cvrPrediction: 0.15,
    imageUrl: "/boutique-hotel-lobby-nautical-theme.jpg",
    tags: ["Boutique", "Waterfront", "Unique"],
  },
  {
    id: "3",
    name: "The Fillmore",
    category: "leisure",
    description: "Historic music venue featuring live concerts, legendary acoustics, and iconic psychedelic posters.",
    rating: 4.7,
    reviewCount: 2156,
    priceRange: "$$",
    distance: "2.1 mi",
    estimatedTime: "25 min",
    relevanceScore: 0.91,
    ctrPrediction: 0.14,
    cvrPrediction: 0.06,
    imageUrl: "/historic-music-venue-concert-hall.jpg",
    tags: ["Live Music", "Historic", "Concerts"],
  },
  {
    id: "4",
    name: "Tartine Bakery",
    category: "dining",
    description: "Artisanal bakery famous for morning buns, sourdough bread, and exceptional pastries made daily.",
    rating: 4.5,
    reviewCount: 1834,
    priceRange: "$$",
    distance: "1.5 mi",
    estimatedTime: "18 min",
    relevanceScore: 0.87,
    ctrPrediction: 0.11,
    cvrPrediction: 0.09,
    imageUrl: "/artisanal-bakery-pastries-display.jpg",
    tags: ["Bakery", "Pastries", "Coffee"],
  },
  {
    id: "5",
    name: "Exploratorium",
    category: "leisure",
    description: "Interactive science museum with hands-on exhibits exploring perception, art, and human phenomena.",
    rating: 4.6,
    reviewCount: 3421,
    priceRange: "$$$",
    distance: "1.8 mi",
    estimatedTime: "22 min",
    relevanceScore: 0.85,
    ctrPrediction: 0.1,
    cvrPrediction: 0.12,
    imageUrl: "/interactive-science-museum-exhibits.jpg",
    tags: ["Science", "Interactive", "Family"],
  },
  {
    id: "6",
    name: "The Ritz-Carlton",
    category: "hospitality",
    description: "Luxury hotel atop Nob Hill offering elegant accommodations, fine dining, and panoramic city views.",
    rating: 4.8,
    reviewCount: 1567,
    priceRange: "$$$$",
    distance: "0.9 mi",
    estimatedTime: "12 min",
    relevanceScore: 0.92,
    ctrPrediction: 0.08,
    cvrPrediction: 0.18,
    imageUrl: "/luxury-hotel-elegant-lobby.jpg",
    tags: ["Luxury", "City Views", "Fine Dining"],
  },
]
